# pylint: disable=C0103,R0801
# Generated by Django 4.2.21 on 2025-05-23 10:23

import django.db.models.deletion
import ovinc_client.core.models
import ovinc_client.core.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VirtualContent",
            fields=[
                (
                    "id",
                    ovinc_client.core.models.UniqIDField(
                        default=ovinc_client.core.utils.uniq_id_without_time,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Name")),
                (
                    "desc",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "allowed_trust_levels",
                    models.JSONField(verbose_name="Allowed Trust Levels"),
                ),
                ("start_time", models.DateTimeField(verbose_name="Start Time")),
                ("end_time", models.DateTimeField(verbose_name="End Time")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "created_by",
                    ovinc_client.core.models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="virtual_contents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Virtual Content",
                "verbose_name_plural": "Virtual Content",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VirtualContentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("content", models.CharField(max_length=255, verbose_name="Content")),
                (
                    "virtual_content",
                    ovinc_client.core.models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="vcd.virtualcontent",
                        verbose_name="Virtual Content",
                    ),
                ),
            ],
            options={
                "verbose_name": "Virtual Content Item",
                "verbose_name_plural": "Virtual Content Item",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="UserShareStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("count", models.BigIntegerField(db_index=True, verbose_name="Count")),
                (
                    "user",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="share_stat",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Share Stats",
                "verbose_name_plural": "User Share Stats",
                "ordering": ["-count"],
            },
        ),
        migrations.CreateModel(
            name="UserReceiveStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("count", models.BigIntegerField(db_index=True, verbose_name="Count")),
                (
                    "user",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receive_stat",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Receive Stats",
                "verbose_name_plural": "User Receive Stats",
                "ordering": ["-count"],
            },
        ),
        migrations.CreateModel(
            name="ReceiveHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Received Time"),
                ),
                ("client_ip", models.GenericIPAddressField(verbose_name="Client IP")),
                ("headers", models.JSONField(verbose_name="Headers")),
                (
                    "receiver",
                    ovinc_client.core.models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receive_histories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Receiver",
                    ),
                ),
                (
                    "virtual_content",
                    ovinc_client.core.models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receive_histories",
                        to="vcd.virtualcontent",
                        verbose_name="Virtual Content",
                    ),
                ),
                (
                    "virtual_content_item",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receive_histories",
                        to="vcd.virtualcontentitem",
                        verbose_name="Virtual Content Item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receive History",
                "verbose_name_plural": "Receive History",
                "ordering": ["-received_at"],
            },
        ),
        migrations.AddIndex(
            model_name="virtualcontentitem",
            index=models.Index(fields=["virtual_content", "id"], name="vcd_virtual_virtual_ba58e9_idx"),
        ),
        migrations.AlterIndexTogether(
            name="virtualcontent",
            index_together={("created_by", "created_at")},
        ),
        migrations.AlterUniqueTogether(
            name="receivehistory",
            unique_together={("virtual_content", "receiver")},
        ),
        migrations.AlterIndexTogether(
            name="receivehistory",
            index_together={("receiver", "received_at")},
        ),
    ]
