# pylint: disable=C0103,R0801
# Generated by Django 4.2.21 on 2025-05-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vcd", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtualcontent",
            name="allow_same_ip",
            field=models.BooleanField(default=True, verbose_name="Allow Same IP"),
        ),
    ]
