# pylint: disable=C0103,R0801
# Generated by Django 4.2.21 on 2025-05-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vcd", "0002_virtualcontent_allow_same_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtualcontent",
            name="allowed_users",
            field=models.JSONField(default=list, verbose_name="Allowed Users"),
        ),
    ]
