# pylint: disable=C0103,R0801
# Generated by Django 4.2.21 on 2025-05-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vcd", "0003_virtualcontent_allowed_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="virtualcontent",
            name="desc",
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name="Description"),
        ),
    ]
