# pylint: disable=C0103,R0801
# Generated by Django 4.2.21 on 2025-05-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vcd", "0005_alter_virtualcontent_end_time"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="virtualcontent",
            new_name="vcd_virtual_created_e03cfc_idx",
            old_fields=("created_by", "created_at"),
        ),
        migrations.AddField(
            model_name="virtualcontent",
            name="is_public_visible",
            field=models.BooleanField(default=False, verbose_name="Is Public Visible"),
        ),
        migrations.AddIndex(
            model_name="virtualcontent",
            index=models.Index(
                fields=["end_time", "is_public_visible"],
                name="vcd_virtual_end_tim_3c583e_idx",
            ),
        ),
    ]
