# pylint: disable=C0103,R0801
# Generated by Django 4.2.21 on 2025-05-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vcd", "0007_alter_virtualcontent_allowed_users"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="virtualcontent",
            name="vcd_virtual_end_tim_3c583e_idx",
        ),
        migrations.RemoveField(
            model_name="virtualcontent",
            name="is_public_visible",
        ),
    ]
