# pylint: disable=C0103,R0801
# Generated by Django 4.2.21 on 2025-06-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vcd", "0008_remove_virtualcontent_vcd_virtual_end_tim_3c583e_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtualcontent",
            name="items_count",
            field=models.BigIntegerField(default=0, verbose_name="Total Items"),
        ),
    ]
