# pylint: disable=C0103,R0801
# Generated by Django 4.2.21 on 2025-06-03 08:47

from django.db import migrations


def sync_exists_vc(*args, **kwargs):
    # pylint: disable=C0415
    from apps.vcd.models import VirtualContent

    virtual_contents: list[VirtualContent] = VirtualContent.objects.all()
    for inst in virtual_contents:
        inst.reload_items()
        inst.items_count = inst.items.count()
        inst.save(update_fields=["items_count"])


class Migration(migrations.Migration):
    dependencies = [
        ("vcd", "0009_virtualcontent_items_count"),
    ]

    operations = [
        migrations.RunPython(sync_exists_vc),
    ]
