# pylint: disable=C0103,R0801
# Generated by Django 4.2.21 on 2025-06-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vcd", "0010_sync_exists_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtualcontent",
            name="show_receiver",
            field=models.BooleanField(default=False, verbose_name="Show Receiver"),
        ),
    ]
