# pylint: disable=C0103,R0801
# Generated by Django 4.2.21 on 2025-06-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vcd", "0011_virtualcontent_show_receiver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="virtualcontentitem",
            name="content",
            field=models.CharField(max_length=1024, verbose_name="Content"),
        ),
    ]
