# pylint: disable=C0103
# Generated by Django 4.2.21 on 2025-05-23 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("email", models.CharField(max_length=255, verbose_name="Email")),
                ("avatar", models.CharField(max_length=255, verbose_name="Avatar")),
                (
                    "trust_level",
                    models.SmallIntegerField(
                        choices=[
                            (0, "New User"),
                            (1, "Basic User"),
                            (2, "User"),
                            (3, "Active User"),
                            (4, "Leader"),
                        ],
                        verbose_name="Trust Level",
                    ),
                ),
                ("api_key", models.CharField(max_length=255, verbose_name="API Key")),
                (
                    "user",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profile",
                "ordering": ["id"],
            },
        ),
    ]
